"""create buy_signals table

Revision ID: 342a92059b5f
Revises: 
Create Date: 2026-04-20 22:23:38.870638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '342a92059b5f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buy_signals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('signal_date', sa.Date(), nullable=False),
    sa.Column('pattern_name', sa.String(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_buy_signals_signal_date', 'buy_signals', ['signal_date'], unique=False)
    op.create_index('idx_buy_signals_status', 'buy_signals', ['status'], unique=False)
    op.create_index('idx_buy_signals_ticker', 'buy_signals', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_buy_signals_ticker', table_name='buy_signals')
    op.drop_index('idx_buy_signals_status', table_name='buy_signals')
    op.drop_index('idx_buy_signals_signal_date', table_name='buy_signals')
    op.drop_table('buy_signals')
    # ### end Alembic commands ###
