"""add interval and signal_datetime to buy_signals

Revision ID: 91ee001dc7dd
Revises: 342a92059b5f
Create Date: 2026-04-24 15:13:42.628338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91ee001dc7dd'
down_revision: Union[str, Sequence[str], None] = '342a92059b5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buy_signals', sa.Column('interval', sa.String(), server_default='1d', nullable=False))
    op.add_column('buy_signals', sa.Column('signal_datetime', sa.DateTime(timezone=True), nullable=True))
    op.create_index('idx_buy_signals_interval', 'buy_signals', ['interval'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_buy_signals_interval', table_name='buy_signals')
    op.drop_column('buy_signals', 'signal_datetime')
    op.drop_column('buy_signals', 'interval')
    # ### end Alembic commands ###
